// ***********************************************************************
// Assembly         : MemTrans.Core
// Author           : Jai Brown
// Created          : 6-2-2024
//
// Last Modified By : Jai Brown
// Last Modified On : 6-2-2024
// ***********************************************************************
// <copyright file="ViewModelBase.cs" company="Jai Brown">
//     Copyright (c) 2024 Jai Brown. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace JaINTP.MemTrans.Core.Mvvm;

using Prism.Mvvm;
using Prism.Navigation;
using Prism.Navigation.Regions;

/// <summary>
///     Basic class for bindable viewmodels.
///     Autogenerated by Prism.
/// </summary>
/// <seealso cref="Prism.Mvvm.BindableBase" />
/// <seealso cref="Prism.Navigation.Regions.INavigationAware" />
/// <seealso cref="Prism.Navigation.IDestructible" />
public class ViewModelBase
    : BindableBase, INavigationAware, IDestructible
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ViewModelBase" /> class.
    /// </summary>
    /// <param name="regionManager">
    ///     The region manager.
    /// </param>
    protected ViewModelBase(IRegionManager regionManager)
    {
        this.RegionManager = regionManager;
    }

    /// <summary>
    ///     Gets the region manager.
    /// </summary>
    /// <value>
    ///     The region manager.
    /// </value>
    protected IRegionManager RegionManager { get; }

    /// <inheritdoc/>
    public virtual void Destroy()
    {
    }

    /// <inheritdoc/>
    public bool IsNavigationTarget(NavigationContext navigationContext)
    {
        return true;
    }

    /// <inheritdoc/>
    public void OnNavigatedFrom(NavigationContext navigationContext)
    {
    }

    /// <inheritdoc/>
    public void OnNavigatedTo(NavigationContext navigationContext)
    {
    }
}